server:
  port: 2525
spring:
  application:
    name: STOCK-PRICE-SERVICE
  datasource:
    username: sa
    password: 
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true