INSERT INTO STOCK_PRICE(STOCK_ID,STOCK_NAME,STOCK_PRICE) VALUES(111,'TCS',79.34);
INSERT INTO STOCK_PRICE(STOCK_ID,STOCK_NAME,STOCK_PRICE) VALUES(222,'HCL',137.54);
INSERT INTO STOCK_PRICE(STOCK_ID,STOCK_NAME,STOCK_PRICE) VALUES(333,'DELL',279.64);
INSERT INTO STOCK_PRICE(STOCK_ID,STOCK_NAME,STOCK_PRICE) VALUES(444,'INFOSYS',879.33);