server:
  port: 1111
management:  endpoints:    web:      exposure:        include: '*'
spring:  application:    name: GREET-ME  boot:    admin:      client:        url: http://localhost:9090